### ISSUE TITLE
Understanding the Concept

### ISSUE THREAD

**Issue by Michaelin007** [SIMPLE-BuildingSimulation/simple_model#4]
Reading this project on rust user lang forum sound interesting to me and I would love to contribute but I'm struggling to understand the concept and the algorithm aspect. I will go through the codes and try to see the area I can fit in. Thanks

**Comment by germolinal** [comment]
Hey! Just a question. From the Rust forum, I got the impression that you wanted to contribute to the [Validate](https://github.com/simPLE-BuildingSimulation/validate) library. Am I wrong?

# SIMPLE Simulation

If you want to learn about SIMPLE, you can start by checking out [THESE VIDEOS](https://www.youtube.com/channel/UCKHUhpFcBo4CAgBqpDtiMEg). I understand everything is a bit obscure at the moment, but I am working more on getting something workable first (not sure if this is a good idea). Anyway, here goes an explanation:

I have been working in Building Simulation Tool space for a number of years now. During this time, I have tried to find ways to combine simulation tools and methods, and also to make simulation more accessible to people. For example, my masters focused on the integration of Radiance and EnergyPlus. It was then when I started developing [Groundhog]([www.groundhoglighting.com](http://www.groundhoglighting.com/)), which intended to put Radiance in everyone’s hands. Developing Groundhog I realized that Radiance could use some sort of wrapper to make it a bit friendlier. This motivated Emp,  a project that has died already. 

During this time I have learned about an enormous amount of undeniable virtues that currently available tools—e.g., EnergyPlus and Radiance—offer to us: they have been extensively validated, they are open source, and so on. Unfortunately, I have also seen many drawbacks. For starters, these tools were not really meant to be embedded on other tools. Radiance confesses this quite clearly:

> “These routines are designed to aid the programmer who wishes to call Radiance as a library.  Unfortunately, the system was not originally intended to be run this way, and there are some awkward limitations to contend with…”
Radiance’s raycalls.c

Also, these tools were developed decades ago. Radiance was developed before the gaming and animation industry invested millions in improving rendering techniques, and EnergyPlus tends to focus too much on building physics even if we now know that we need to pay more attention to people’s behaviour in buildings (because insulating an open door is pointless). Also, programming was different back then, with different source control systems and way less people who knew how to code.

Because of all this, I am trying to develop a new simulation tool: SIMPLE Simulation Tools. Don’t be mistaken, though, I am not proposing to reinvent the wheel. The wheel—i.e., the knowledge of physics and rendering and computer sciences—is all available… what we need to do is to build a wheel with new materials and methods.

# [Validate library](https://github.com/simPLE-BuildingSimulation/validate)

The whole purpose of this is that—because SIMPLE is about numerical results that should match real-life measurements—I need a systematic way of ensuring that, whatever changes I introduce, keep SIMPLE physically valid. (For now, validations are performed against [EnergyPlus'](https://energyplus.net) results and analytical equations that can be derived from currently existing—and widely known—mathematical models of heat transfer.

So, Validate becomes a library that helps disclose Validations and also integrate those checks/tests into the Continuous integration. For example, [this report](https://simple-buildingsimulation.github.io/thermal/validation/walls.html) is automatically produced when pushing the thermal module of SIMPLE.

**Comment by Michaelin007** [comment]
You are not wrong. Gonna go through the resources

**Comment by germolinal** [comment]
I am closing this then. Please submit to the other repo
